language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/tcptest/tcptest.cpp

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --board=uno --board=diecimilaatmega328 --board=pro16MHzatmega328
